server:
  port: 8181

spring:
  application:
    name: user-service

  datasource:
    username: root
    password: secret
    url: jdbc:mysql://localhost:3306/homestay

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka